- name: Download agent2.service debian
  get_url:
    url: https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-4+debian10_all.deb
    dest: ./zabbix-release_6.2-4+debian10_all.deb
  when: os_family_type == "debian"

- name: Download agent2.service debian
  shell: | 
    dpkg -i ./zabbix-release_6.2-4+debian10_all.deb
    apt update
  when: os_family_type == "debian"

- name: Install agent2.service debian
  apt:
    name: zabbix-agent2
    update_cache: yes
  when: os_family_type == "debian"

- name: Download agent2 redhat
  yum:
    name: https://repo.zabbix.com/zabbix/6.2/rhel/7/x86_64/zabbix-release-6.2-3.el7.noarch.rpm
  when: os_family_type == "redhat"

- name: Yum clean all
  shell: yum clean all
  when: os_family_type == "redhat"

- name: Install agent2.service redhat
  yum:
    name: zabbix-agent2
  when: os_family_type == "redhat"
